import { StrictMode } from 'react'
import { createRoot } from 'react-dom/client'
import './styles/vars.css'
import './styles/base.css'
import './styles/navbar.css'
import './styles/hero.css'
import './styles/trust.css'
import './styles/services.css'
import './styles/dyno.css'
import './styles/about.css'
import './styles/karting.css'
import './styles/process.css'
import './styles/sections.css'
import './styles/gallery.css'
import './styles/testimonials.css'
import './styles/faq.css'
import './styles/form.css'
import './styles/location.css'
import './styles/footer.css'
import './styles/responsive.css'
import App from './App.jsx'
createRoot(document.getElementById('root')).render(<StrictMode><App /></StrictMode>)
